steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "create superuser"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SUPERUSER_CREDENTIALS=${_SUPERUSER_CREDENTIALS}",
        "-e",
        "GOOGLE_CLOUD_PROJECT=$PROJECT_ID",
        "--",
        "python",
        "manage.py",
        "create_superuser_from_secrets"
      ]

substitutions:
  _INSTANCE_NAME: db-instance
  _REGION: us-central1
  _SERVICE_NAME: polls-service
  _SUPERUSER_CREDENTIALS: superuser_credentials

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
